'use client';
import { useEffect, useRef, useState, type PointerEvent as ReactPointerEvent } from 'react';
import { RotateCw, Trophy, Volume2, VolumeX, HelpCircle, X, ArrowUpRight, Sparkles, Bomb, Check } from 'lucide-react';
import { fresh, rotate, fits, canPlay, place, restoreSave, bombArea, detonate, previewLines, type Game, type Shape } from '../lib/game';
import {playEffect,type SoundKind} from '../lib/audio';
import PwaStatus from './pwa-status';
import { touchPlacement, touchReturned } from '../lib/drag';
type Drag = { index:number; x:number; y:number; row:number; col:number; size:number };
const initial:Game={board:Array.from({length:8},()=>Array(8).fill(0)),pieces:[{shape:[[1,0],[1,0],[1,1]],color:1},{shape:[[1,1,1],[0,1,0]],color:2},{shape:[[1,1],[1,1]],color:3}],score:0,lines:0,combo:0,bombs:0,goldenBomb:false};
function Blocks({shape,color,size=23}:{shape:Shape;color:number;size?:number}) { return <span className="shape" style={{gridTemplateColumns:`repeat(${shape[0].length}, ${size}px)`,gridAutoRows:size}}>{shape.flatMap((r,y)=>r.map((v,x)=><span key={`${y}-${x}`} className={v?`block color-${color}`:'void'}/>))}</span>; }
export default function Home(){
 const [game,setGame]=useState<Game>(initial);const [ready,setReady]=useState(false);const [best,setBest]=useState(0);const [sound,setSound]=useState(false);const [modal,setModal]=useState<'help'|'restart'|null>(null);const [selected,setSelected]=useState<number|null>(null);const [drag,setDrag]=useState<Drag|null>(null);const [flash,setFlash]=useState<number[]>([]);const [notice,setNotice]=useState('');const [celebration,setCelebration]=useState(0);const [celebrationReward,setCelebrationReward]=useState(false);const celebrationTimer=useRef<ReturnType<typeof setTimeout>|null>(null);
 const trayRef=useRef<HTMLDivElement>(null);const boardRef=useRef<HTMLDivElement>(null);const active=useRef<{index:number;pointerId:number;x:number;y:number;originX:number;moving:boolean;touch:boolean;drag:Drag|null}|null>(null);const current=useRef(game);current.current=game;const timer=useRef<ReturnType<typeof setTimeout>|null>(null);const audio=useRef<AudioContext|null>(null);const soundEnabled=useRef(false);
 useEffect(()=>{try{const saved=restoreSave(JSON.parse(localStorage.getItem('block-turn-game')||'null'));if(saved)setGame(saved);else setGame(fresh());const b=Number(localStorage.getItem('block-turn-best'));if(Number.isSafeInteger(b)&&b>0)setBest(b);}catch{setGame(fresh());}setReady(true);return()=>{if(timer.current)clearTimeout(timer.current);if(celebrationTimer.current)clearTimeout(celebrationTimer.current);};},[]);
 useEffect(()=>{if(!ready)return;try{localStorage.setItem('block-turn-game',JSON.stringify(game));const record=Math.max(best,game.score);localStorage.setItem('block-turn-best',String(record));if(record>best)setBest(record);}catch{}},[game,ready,best]);
 useEffect(()=>{const area=document.querySelector('.play-area');if(!area)return;const preventSelection=(event:Event)=>event.preventDefault();area.addEventListener('selectstart',preventSelection);return()=>area.removeEventListener('selectstart',preventSelection);},[]);
 // Non-passive touch listeners suppress Safari's native long-press handling.
 // These controls act on pointerup, so suppressing synthetic clicks is intentional.
 useEffect(()=>{const zones=document.querySelectorAll('.waiting-zone, .header-bombs');const suppress=(event:Event)=>{if(event.cancelable)event.preventDefault();};zones.forEach(zone=>{zone.addEventListener('touchstart',suppress,{passive:false});zone.addEventListener('touchmove',suppress,{passive:false});});return()=>zones.forEach(zone=>{zone.removeEventListener('touchstart',suppress);zone.removeEventListener('touchmove',suppress);});},[]);
 const over=ready&&!canPlay(game);
 function play(kind:SoundKind){if(!soundEnabled.current)return;try{const a=audio.current?.state==='closed'?null:audio.current;audio.current=a??new AudioContext();void playEffect(audio.current,kind,()=>soundEnabled.current).catch(()=>{soundEnabled.current=false;setSound(false);message('Не удалось включить звук. Нажми ещё раз.');});}catch{soundEnabled.current=false;setSound(false);message('Звук недоступен в этом браузере');}}
 function toggleSound(){const enabled=!soundEnabled.current;soundEnabled.current=enabled;setSound(enabled);try{const session=(navigator as Navigator & {audioSession?:{type:string}}).audioSession;if(session)session.type=enabled?'playback':'auto';}catch{}if(enabled)play('move');else if(audio.current)void audio.current.suspend().catch(()=>{});}
 function tone(clear=false){play(clear?'clear':'move');}
 function message(text:string,cells:number[]=[]){setNotice(text);setFlash(cells);if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(()=>{setNotice('');setFlash([]);},650);}
 function celebrate(reward:boolean){setCelebrationReward(reward);setCelebration(n=>n+1);if(celebrationTimer.current)clearTimeout(celebrationTimer.current);celebrationTimer.current=setTimeout(()=>setCelebration(0),1200);play('celebrate');}
 function turn(index:number){if(modal||over)return;setGame(g=>({...g,pieces:g.pieces.map((p,i)=>p&&i===index?{...p,shape:rotate(p.shape)}:p)}));setSelected(index);tone();}
 function put(index:number,row:number,col:number){if(modal)return false;const previous=current.current;const result=index===-1?detonate(previous,row,col):place(previous,index,row,col);if(!result)return false;current.current=result.game;setGame(result.game);setSelected(null);if(result.allClear)celebrate(index!==-1);else tone(result.cleared.length>0);message(index===-1?`БОМБА · +${result.points}`:result.game.bombs>previous.bombs?`КОМБО ×${result.game.combo} · +1 БОМБА`:result.cleared.length?`${result.game.combo>1?'КОМБО ×'+result.game.combo+' · ':''}+${result.points}`:`+${result.points}`,result.cleared);return true;}
 function newGame(){setGame(fresh());setModal(null);setSelected(null);setDrag(null);active.current=null;setNotice('');setFlash([]);setCelebration(0);if(celebrationTimer.current)clearTimeout(celebrationTimer.current);}
 function pointerPosition(index:number,x:number,y:number):Drag|null{
  const rect=boardRef.current?.firstElementChild?.getBoundingClientRect(),p=index===-1?{shape:[[1]]}:current.current.pieces[index];
  if(!rect||!p)return null;
  const size=rect.width+4,a=active.current;
  if(a?.touch){const pos=touchPlacement(x-a.x,y-a.y,size,p.shape[0].length,p.shape.length,index===-1,a.originX-rect.left);return {index,x:rect.left+pos.left,y:rect.top+pos.top,row:pos.row,col:pos.col,size};}
  const left=x-p.shape[0].length*size/2,top=y-p.shape.length*size/2;
  return {index,x:left,y:top,row:Math.round((top-rect.top)/size),col:Math.round((left-rect.left)/size),size};
 }
 function dragHandlers(index:number){return {
  onPointerDown:(e:ReactPointerEvent<HTMLButtonElement>)=>{if(e.button!==0||active.current)return;e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);const slot=e.currentTarget.getBoundingClientRect();active.current={originX:slot.left+slot.width/2,index,pointerId:e.pointerId,x:e.clientX,y:e.clientY,moving:false,touch:e.pointerType==='touch',drag:null};},
  onPointerMove:(e:ReactPointerEvent<HTMLButtonElement>)=>{const a=active.current;if(!a||a.index!==index||a.pointerId!==e.pointerId)return;if(Math.hypot(e.clientX-a.x,e.clientY-a.y)>7)a.moving=true;if(a.moving){a.drag=pointerPosition(index,e.clientX,e.clientY);setDrag(a.drag);}},
  onPointerUp:(e:ReactPointerEvent<HTMLButtonElement>)=>{const a=active.current;if(!a||a.pointerId!==e.pointerId)return;const d=a.moving?pointerPosition(index,e.clientX,e.clientY):null;active.current=null;setDrag(null);
   if(!a.moving){if(index===-1)setSelected(s=>s===-1?null:-1);else turn(index);return;}
   const tray=trayRef.current?.getBoundingClientRect();
   const returned=a.touch?!!d&&touchReturned(d.row,index===-1?1:current.current.pieces[index]!.shape.length,index===-1):!!tray&&e.clientX>=tray.left&&e.clientX<=tray.right&&e.clientY>=tray.top&&e.clientY<=tray.bottom;
   if(returned)return;
   if(d&&!put(index,d.row,d.col))message('Попробуй другое место');
  },
  onPointerCancel:(e:ReactPointerEvent<HTMLButtonElement>)=>{if(active.current?.pointerId===e.pointerId){active.current=null;setDrag(null);}},
  onLostPointerCapture:(e:ReactPointerEvent<HTMLButtonElement>)=>{if(active.current?.pointerId===e.pointerId){active.current=null;setDrag(null);}}
 };}
 useEffect(()=>{const ctx=(document as Document & {modelContext?:{registerTool:(t:unknown,o:unknown)=>Promise<void>|void}}).modelContext;if(!ctx)return;const life=new AbortController();for(const t of [{name:'read_game',description:'Read the block puzzle board, waiting pieces and score.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>current.current},{name:'rotate_waiting_piece',description:'Rotate a waiting piece clockwise by 90 degrees.',inputSchema:{type:'object',properties:{index:{type:'integer',minimum:0,maximum:2}},required:['index'],additionalProperties:false},execute:(input:{index:number})=>{if(!Number.isInteger(input.index)||!current.current.pieces[input.index])throw Error('No waiting piece at this index');const g={...current.current,pieces:current.current.pieces.map((p,i)=>p&&i===input.index?{...p,shape:rotate(p.shape)}:p)};current.current=g;setGame(g);return g.pieces[input.index];}}]){try{void Promise.resolve(ctx.registerTool(t,{signal:life.signal})).catch(()=>{});}catch{}}return()=>life.abort();},[]);
 const ghost=drag&&(drag.index===-1?{shape:[[1]],color:2}:game.pieces[drag.index]);const blast=drag?.index===-1?bombArea(drag.row,drag.col,game.goldenBomb?5:3):[];const valid=drag&&ghost&&(drag.index===-1?blast.length>0:fits(game.board,ghost.shape,drag.row,drag.col));
 const linePreview=drag&&ghost&&drag.index!==-1?previewLines(game.board,ghost.shape,drag.row,drag.col):[];
 return <main className="shell"><header className="topbar"><a className="brand" href={`${process.env.NEXT_PUBLIC_BASE_PATH||''}/`} aria-label="Block Turn — главная"><span className="brand-icon"><i/><i/><i/><i/></span>block<span>turn</span><sup>↻</sup></a><span className="top-caption">МАЛЕНЬКИЙ ПОВОРОТ. НОВЫЕ ВОЗМОЖНОСТИ.</span><button className="icon-button" aria-label="Правила игры" onClick={()=>setModal('help')}><HelpCircle size={20}/></button></header>
 <section className="game-layout"><aside className="intro"><div className="eyebrow"><span/> КЛАССИКА С ПОВОРОТОМ</div><h1>Всё в твоих<br/><em>поворотах.</em></h1><p>Собирай линии. Освобождай поле.<br/>Находи место для каждой фигуры.</p><div className="tip-card"><span className="tip-icon"><RotateCw size={25}/></span><div><strong>Не помещается? Поверни.</strong><p>Нажми на фигуру внизу,<br/>чтобы повернуть её на 90°.</p></div></div><div className="mini-instruction"><span>01</span> Нажми, чтобы повернуть.<br/><span>02</span> Перетащи на поле.<br/><span>03</span> Заполни строку или столбец.</div><div className="relax"><span/> Без таймера. В своём ритме.</div></aside>
 <section className="play-area" aria-label="Игра Block Turn" onContextMenu={e=>e.preventDefault()}><div className="scorebar"><div><span className="score-label">ТВОЙ СЧЁТ</span><strong className="score">{game.score.toLocaleString('ru-RU')}</strong></div><div className="header-bombs"><button className={`bomb-button ${game.bombs===1?'available':''} ${game.goldenBomb?'golden':''} ${selected===-1?'armed':''}`} disabled={!ready||game.bombs===0||!!modal} aria-label={game.bombs===1?`${game.goldenBomb?'Золотая бомба 5×5':'Бомба 3×3'} доступна. Перетащите на поле или нажмите для выбора`:'Бомбы нет. Очистите линии три хода подряд'} title={game.bombs===1?`${game.goldenBomb?'Золотая бомба 5×5':'Бомба 3×3'} — перетащи на поле`:'Бомба за три хода подряд с очисткой'} aria-pressed={selected===-1} {...dragHandlers(-1)} onClick={e=>{if(e.detail===0)setSelected(s=>s===-1?null:-1);}} onKeyDown={e=>{if(e.key==='Escape')setSelected(null);}}><Bomb size={23}/>{game.goldenBomb&&<span className="gold-star" aria-hidden="true">✦</span>}</button></div><div className="record"><Trophy size={17}/><span>РЕКОРД<strong>{best.toLocaleString('ru-RU')}</strong></span></div><button className="icon-button" onClick={toggleSound} aria-pressed={sound} aria-label={sound?'Выключить звук':'Включить звук'}>{sound?<Volume2 size={19}/>:<VolumeX size={19}/>}</button></div>
 <div className="board-wrap"><div ref={boardRef} className="board" role="group" aria-label="Поле 8 на 8">{game.board.flatMap((r,y)=>r.map((v,x)=>{const highlighted=drag?.index===-1?blast.includes(y*8+x):!!(drag&&ghost&&ghost.shape[y-drag.row]?.[x-drag.col]);return <button key={y*8+x} className={`cell ${v?'block color-'+v:''} ${highlighted?(valid?'preview color-'+ghost!.color:'invalid'):''} ${flash.includes(y*8+x)?'cleared':''} ${linePreview.includes(y*8+x)?'line-preview':''}`} aria-label={`Строка ${y+1}, столбец ${x+1}, ${v?'занято':'свободно'}`} onClick={()=>{if(selected!==null&&!over&&!put(selected,y,x))message('Здесь не помещается');}}/>;}))}</div>{celebration>0&&<div key={celebration} className="all-clear" role="status"><div className="clear-wave"/>{Array.from({length:12},(_,i)=><i className="clear-spark" key={i} style={{left:`${8+(i*29)%84}%`,top:`${12+(i*37)%72}%`,animationDelay:`${i*.025}s`}}>✦</i>)}<div className="clear-title">Чистая работа!<small>{celebrationReward?'Золотая бомба 5×5 готова':'Поле полностью очищено'}</small></div></div>}<div className={`score-pop ${notice?'show':''}`} role="status">{notice}</div>{over&&<div className="game-over"><Sparkles size={30}/><h2>Хорошая партия!</h2><p>Для оставшихся фигур нет места,<br/>а бомбы закончились.</p><strong>{game.score} <small>очков</small></strong><button className="primary" onClick={newGame}>Сыграть ещё <ArrowUpRight size={19}/></button></div>}</div>
 <div className="tray-heading"><span>ТВОИ ФИГУРЫ</span><span><RotateCw size={13}/> касание = поворот</span></div><div className="waiting-zone" ref={trayRef}><div className="tray">{game.pieces.map((p,index)=><button key={index} className={`piece-slot ${selected===index?'selected':''} ${drag?.index===index?'dragging':''}`} disabled={!p||over||!ready||!!modal} aria-label={p?`Фигура ${index+1}. Нажмите для поворота или перетащите на поле`:'Фигура установлена'} onKeyDown={e=>{if(e.key==='Escape')setSelected(null);}} onClick={e=>{if(e.detail===0&&p)turn(index);}} {...dragHandlers(index)}>{p?<><Blocks shape={p.shape} color={p.color}/><RotateCw className="rotate-hint" size={14}/></>:<span className="used" aria-hidden="true"><Check size={24}/></span>}</button>)}</div></div>
 <p className="mobile-tip">{selected===-1?'Нажми на поле, чтобы взорвать бомбу.':'Касание — поворот. Веди палец, чтобы поставить фигуру.'}</p><div className="game-footer"><span><span className="status-dot"/> {game.lines} {game.lines===1?'линия':'линий'} собрано</span><button onClick={()=>setModal('restart')}><RotateCw size={15}/> Новая игра</button></div><PwaStatus/></section><div className="right-note"><span>↻</span><p>Другой угол.<br/>Новый ход.</p></div></section><footer className="page-footer"><span>BLOCK TURN</span><span>Ещё один ход — и всё сложится.</span><span>8 × 8 / БЕЗ СПЕШКИ</span></footer>
 {drag&&ghost&&<div className="floating-piece" style={{left:drag.x,top:drag.y}}>{drag.index===-1?<span className={`flying-bomb ${game.goldenBomb?'golden':''}`} style={{width:drag.size,height:drag.size}}><Bomb size={32}/></span>:<Blocks shape={ghost.shape} color={ghost.color} size={drag.size-4}/>}</div>}
 {modal&&<div className="modal-backdrop" onClick={()=>setModal(null)}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="dialog-title" onClick={e=>e.stopPropagation()} onKeyDown={e=>{if(e.key==='Escape')setModal(null);}}><button autoFocus className="icon-button close" aria-label="Закрыть" onClick={()=>setModal(null)}><X size={21}/></button><RotateCw className="modal-icon" size={32}/><h2 id="dialog-title">{modal==='help'?'Каждый поворот — возможность':'Начать заново?'}</h2>{modal==='help'?<><p>Перетаскивай фигуры на свободные клетки. Полностью заполненные строки и столбцы исчезают.</p><p><b>Нажатие на фигуру в зоне ожидания поворачивает её на 90°.</b> Вращать можно сколько угодно. На поле фигуры уже неподвижны.</p><p>После трёх установленных фигур появятся новые. Очищай линии ход за ходом, чтобы получать бонус за комбо.</p><p>На старте бомбы нет. Каждые три установки фигур подряд с очисткой линий дают бомбу, если её ещё нет. Можно хранить только одну. Серая кнопка означает, что бомбы нет, подсвеченная — что она готова: перетащи бомбу в любое место поля или выбери её и нажми клетку. Взрыв очищает квадрат 3×3, у края он сдвигается внутрь поля. Бомба не сбрасывает серию и не продвигает её.</p><p>Полностью очисти поле установкой фигуры, чтобы получить золотую бомбу 5×5. Очистка взрывом новую бомбу не даёт. Она заменяет обычную: хранится по-прежнему только одна. Повторный взрыв на уже пустом поле награду не даёт.</p><p>На телефоне фигура перемещается относительно движения пальца с небольшим усилением ×1,5. Заведи её на поле снизу. Чтобы отменить перенос, выведи фигуру обратно за нижний край. Бомба переносится сверху; её также можно выбрать нажатием, а затем нажать нужную клетку.</p><p className="muted">Можно играть без перетаскивания: выбери фигуру нажатием, затем нажми клетку для её верхнего левого угла. С клавиатуры — Tab и Enter.</p><button className="primary" onClick={()=>setModal(null)}>Всё понятно, играем</button></>:<><p>Текущая партия завершится. Рекорд сохранится.</p><button className="primary" onClick={newGame}>Начать новую игру</button><button className="secondary" onClick={()=>setModal(null)}>Продолжить партию</button></>}</section></div>}
 </main>;
}
