'use client';
import { useEffect, useRef, useState, useMemo, type CSSProperties, type PointerEvent as ReactPointerEvent } from 'react';
import { RotateCw, Trophy, Volume2, VolumeX, HelpCircle, X, ArrowUpRight, Sparkles, Bomb, Check, Shuffle } from 'lucide-react';
import { fresh, placementRisk, rerollPiece, bombIsLastResort, rotate, fits, canPlay, place, restoreSave, bombArea, detonate, previewLines, type Game, type Shape } from '../lib/game';
import {playEffect,type SoundKind} from '../lib/audio';
import {moveEvent} from '../lib/events';
import PwaStatus from './pwa-status';
import { touchPlacement, touchReturned } from '../lib/drag';
type Drag = { index:number; x:number; y:number; row:number; col:number; size:number };
const initial:Game={board:Array.from({length:8},()=>Array(8).fill(0)),pieces:[{shape:[[1,0],[1,0],[1,1]],color:1},{shape:[[1,1,1],[0,1,0]],color:2},{shape:[[1,1],[1,1]],color:3}],score:0,lines:0,combo:0,bombs:0,goldenBomb:false,rerolls:0};
function Blocks({shape,color,size=23}:{shape:Shape;color:number;size?:number}) { return <span className="shape" style={{gridTemplateColumns:`repeat(${shape[0].length}, ${size}px)`,gridAutoRows:size}}>{shape.flatMap((r,y)=>r.map((v,x)=><span key={`${y}-${x}`} className={v?`block color-${color}`:'void'}/>))}</span>; }
export default function Home(){
 const [game,setGame]=useState<Game>(initial);const [ready,setReady]=useState(false);const [best,setBest]=useState(0);const [sound,setSound]=useState(false);const [modal,setModal]=useState<'help'|'restart'|null>(null);const [selected,setSelected]=useState<number|null>(null);const [drag,setDrag]=useState<Drag|null>(null);const [flash,setFlash]=useState<number[]>([]);const [notice,setNotice]=useState('');const [event,setEvent]=useState<(NonNullable<ReturnType<typeof moveEvent>>&{id:number;points:number})|null>(null);const eventId=useRef(0);const eventTimer=useRef<ReturnType<typeof setTimeout>|null>(null);
 const [rerollMode,setRerollMode]=useState(false);const [swapping,setSwapping]=useState<number|null>(null);const [rotating,setRotating]=useState<number|null>(null);const [rotationVersion,setRotationVersion]=useState(0);const rotationTimer=useRef<ReturnType<typeof setTimeout>|null>(null);const [hand,setHand]=useState(0);const [stamped,setStamped]=useState<number[]>([]);const [clearRows,setClearRows]=useState<number[]>([]);const [clearCols,setClearCols]=useState<number[]>([]);
 const motionTimer=useRef<ReturnType<typeof setTimeout>|null>(null);const stampTimer=useRef<ReturnType<typeof setTimeout>|null>(null);
 useEffect(()=>{const cancel=(e:KeyboardEvent)=>{if(e.key==='Escape'){setRerollMode(false);setSelected(null);}};window.addEventListener('keydown',cancel);return()=>{window.removeEventListener('keydown',cancel);if(rotationTimer.current)clearTimeout(rotationTimer.current);if(motionTimer.current)clearTimeout(motionTimer.current);if(stampTimer.current)clearTimeout(stampTimer.current);};},[]);
 const trayRef=useRef<HTMLDivElement>(null);const boardRef=useRef<HTMLDivElement>(null);const active=useRef<{index:number;pointerId:number;x:number;y:number;originX:number;moving:boolean;touch:boolean;drag:Drag|null}|null>(null);const current=useRef(game);current.current=game;const timer=useRef<ReturnType<typeof setTimeout>|null>(null);const audio=useRef<AudioContext|null>(null);const soundEnabled=useRef(false);
 useEffect(()=>{try{const saved=restoreSave(JSON.parse(localStorage.getItem('block-turn-game')||'null'));if(saved)setGame(saved);else setGame(fresh());const b=Number(localStorage.getItem('block-turn-best'));if(Number.isSafeInteger(b)&&b>0)setBest(b);}catch{setGame(fresh());}setReady(true);return()=>{if(timer.current)clearTimeout(timer.current);if(eventTimer.current)clearTimeout(eventTimer.current);};},[]);
 useEffect(()=>{if(!ready)return;try{localStorage.setItem('block-turn-game',JSON.stringify(game));const record=Math.max(best,game.score);localStorage.setItem('block-turn-best',String(record));if(record>best)setBest(record);}catch{}},[game,ready,best]);
 useEffect(()=>{const area=document.querySelector('.play-area');if(!area)return;const preventSelection=(event:Event)=>event.preventDefault();area.addEventListener('selectstart',preventSelection);return()=>area.removeEventListener('selectstart',preventSelection);},[]);
 // Non-passive touch listeners suppress Safari's native long-press handling.
 // These controls act on pointerup, so suppressing synthetic clicks is intentional.
 useEffect(()=>{const zones=document.querySelectorAll('.waiting-zone, .header-bombs');const suppress=(event:Event)=>{if(event.cancelable)event.preventDefault();};zones.forEach(zone=>{zone.addEventListener('touchstart',suppress,{passive:false});zone.addEventListener('touchmove',suppress,{passive:false});});return()=>zones.forEach(zone=>{zone.removeEventListener('touchstart',suppress);zone.removeEventListener('touchmove',suppress);});},[]);
 const over=ready&&!canPlay(game);
 const [showGameOver,setShowGameOver]=useState(false);
 useEffect(()=>{setShowGameOver(false);if(!over)return;const timeout=setTimeout(()=>setShowGameOver(true),window.matchMedia('(prefers-reduced-motion: reduce)').matches?0:750);return()=>clearTimeout(timeout);},[over]);
 function play(kind:SoundKind){if(!soundEnabled.current)return;try{const a=audio.current?.state==='closed'?null:audio.current;audio.current=a??new AudioContext();void playEffect(audio.current,kind,()=>soundEnabled.current).catch(()=>{soundEnabled.current=false;setSound(false);message('Не удалось включить звук. Нажми ещё раз.');});}catch{soundEnabled.current=false;setSound(false);message('Звук недоступен в этом браузере');}}
 function toggleSound(){const enabled=!soundEnabled.current;soundEnabled.current=enabled;setSound(enabled);try{const session=(navigator as Navigator & {audioSession?:{type:string}}).audioSession;if(session)session.type=enabled?'playback':'auto';}catch{}if(enabled)play('move');else if(audio.current)void audio.current.suspend().catch(()=>{});}
 function tone(clear=false){play(clear?'clear':'move');}
 function message(text:string,cells:number[]=[]){setNotice(text);setFlash(cells);if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(()=>{setNotice('');setFlash([]);},650);}

 function toggleReroll(){if(!game.rerolls||modal||swapping!==null||active.current)return;setRerollMode(v=>!v);setSelected(null);setDrag(null);active.current=null;}
 function replacePiece(index:number){
  if(swapping!==null||modal)return;const next=rerollPiece(current.current,index);if(!next){message('Нет места для замены');return;}
  setRerollMode(false);setSelected(null);setSwapping(index);play('reroll');
  motionTimer.current=setTimeout(()=>{current.current=next;setGame(next);motionTimer.current=setTimeout(()=>setSwapping(null),180);},120);
 }
 function turn(index:number){if(rerollMode){replacePiece(index);return;}if(modal||over||swapping!==null)return;
  const g=current.current;if(!g.pieces[index])return;
  const next={...g,pieces:g.pieces.map((p,i)=>p&&i===index?{...p,shape:rotate(p.shape)}:p)};
  current.current=next;setGame(next);setRotating(index);setRotationVersion(n=>n+1);setSelected(index);tone();
  if(rotationTimer.current)clearTimeout(rotationTimer.current);rotationTimer.current=setTimeout(()=>setRotating(null),70);
 }
 function put(index:number,row:number,col:number){
  if(modal||rerollMode||swapping!==null)return false;const previous=current.current;const result=index===-1?detonate(previous,row,col):place(previous,index,row,col);if(!result)return false;
  const rows=result.rowsCleared,cols=result.colsCleared;
  setClearRows(rows);setClearCols(cols);
  const cells:number[]=[];if(index>=0)previous.pieces[index]?.shape.forEach((r,y)=>r.forEach((v,x)=>{if(v)cells.push((row+y)*8+col+x);}));
  setStamped(cells);if(stampTimer.current)clearTimeout(stampTimer.current);stampTimer.current=setTimeout(()=>setStamped([]),450);
  if(index>=0&&previous.pieces.filter(Boolean).length===1)setHand(n=>n+1);
  current.current=result.game;setGame(result.game);setSelected(null);
  const highlight=moveEvent(previous,result.game,result.allClear,index!==-1,rows,cols);
  if(eventTimer.current)clearTimeout(eventTimer.current);setEvent(highlight?{...highlight,details:highlight.details,points:result.points,id:++eventId.current}:null);
  if(highlight)eventTimer.current=setTimeout(()=>setEvent(null),highlight.duration);
  if(highlight?.classification)play(highlight.classification==='perfect'?'perfect':highlight.tier===3?'celebrate':highlight.tier===2?'harmony':'bright');else tone(result.cleared.length>0);
  message(highlight?.title?'':`${index===-1?'БОМБА · ':result.game.combo>=2?'КОМБО ×'+result.game.combo+' · ':''}+${result.points}`,result.cleared);return true;
 }
 function newGame(){if(motionTimer.current)clearTimeout(motionTimer.current);setSwapping(null);setRotating(null);setRerollMode(false);setStamped([]);setHand(n=>n+1);setEvent(null);if(eventTimer.current)clearTimeout(eventTimer.current);setGame(fresh());setModal(null);setSelected(null);setDrag(null);active.current=null;setNotice('');setFlash([]);}
 function pointerPosition(index:number,x:number,y:number):Drag|null{
  const rect=boardRef.current?.firstElementChild?.getBoundingClientRect(),p=index===-1?{shape:[[1]]}:current.current.pieces[index];
  if(!rect||!p)return null;
  const size=rect.width+4,a=active.current;
  if(a?.touch){const pos=touchPlacement(x-a.x,y-a.y,size,p.shape[0].length,p.shape.length,index===-1,a.originX-rect.left);return {index,x:rect.left+pos.left,y:rect.top+pos.top,row:pos.row,col:pos.col,size};}
  const left=x-p.shape[0].length*size/2,top=y-p.shape.length*size/2;
  return {index,x:left,y:top,row:Math.round((top-rect.top)/size),col:Math.round((left-rect.left)/size),size};
 }
 function dragHandlers(index:number){return {
  onPointerDown:(e:ReactPointerEvent<HTMLButtonElement>)=>{if(e.button!==0||active.current||swapping!==null||modal||over)return;if(rerollMode){e.preventDefault();if(index>=0)replacePiece(index);else setRerollMode(false);return;}e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);const slot=e.currentTarget.getBoundingClientRect();active.current={originX:slot.left+slot.width/2,index,pointerId:e.pointerId,x:e.clientX,y:e.clientY,moving:false,touch:e.pointerType==='touch',drag:null};},
  onPointerMove:(e:ReactPointerEvent<HTMLButtonElement>)=>{const a=active.current;if(!a||a.index!==index||a.pointerId!==e.pointerId)return;if(Math.hypot(e.clientX-a.x,e.clientY-a.y)>7)a.moving=true;if(a.moving){a.drag=pointerPosition(index,e.clientX,e.clientY);setDrag(a.drag);}},
  onPointerUp:(e:ReactPointerEvent<HTMLButtonElement>)=>{const a=active.current;if(!a||a.pointerId!==e.pointerId)return;const d=a.moving?pointerPosition(index,e.clientX,e.clientY):null;active.current=null;setDrag(null);
   if(!a.moving){if(index===-1)setSelected(s=>s===-1?null:-1);else turn(index);return;}
   const tray=trayRef.current?.getBoundingClientRect();
   const returned=a.touch?!!d&&touchReturned(d.row,index===-1?1:current.current.pieces[index]!.shape.length,index===-1):!!tray&&e.clientX>=tray.left&&e.clientX<=tray.right&&e.clientY>=tray.top&&e.clientY<=tray.bottom;
   if(returned)return;
   if(d&&!put(index,d.row,d.col))message('Попробуй другое место');
  },
  onPointerCancel:(e:ReactPointerEvent<HTMLButtonElement>)=>{if(active.current?.pointerId===e.pointerId){active.current=null;setDrag(null);}},
  onLostPointerCapture:(e:ReactPointerEvent<HTMLButtonElement>)=>{if(active.current?.pointerId===e.pointerId){active.current=null;setDrag(null);}}
 };}
 useEffect(()=>{const ctx=(document as Document & {modelContext?:{registerTool:(t:unknown,o:unknown)=>Promise<void>|void}}).modelContext;if(!ctx)return;const life=new AbortController();for(const t of [{name:'read_game',description:'Read the block puzzle board, waiting pieces and score.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>current.current},{name:'rotate_waiting_piece',description:'Rotate a waiting piece clockwise by 90 degrees.',inputSchema:{type:'object',properties:{index:{type:'integer',minimum:0,maximum:2}},required:['index'],additionalProperties:false},execute:(input:{index:number})=>{if(!Number.isInteger(input.index)||!current.current.pieces[input.index])throw Error('No waiting piece at this index');const g={...current.current,pieces:current.current.pieces.map((p,i)=>p&&i===input.index?{...p,shape:rotate(p.shape)}:p)};current.current=g;setGame(g);return g.pieces[input.index];}}]){try{void Promise.resolve(ctx.registerTool(t,{signal:life.signal})).catch(()=>{});}catch{}}return()=>life.abort();},[]);
 const bombOnly=bombIsLastResort(game);
 const ghost=drag&&(drag.index===-1?{shape:[[1]],color:2}:game.pieces[drag.index]);const blast=drag?.index===-1?bombArea(drag.row,drag.col,game.goldenBomb?5:3):[];const valid=drag&&ghost&&(drag.index===-1?blast.length>0:fits(game.board,ghost.shape,drag.row,drag.col));
 const risk=useMemo(()=>drag&&drag.index>=0?placementRisk(game,drag.index,drag.row,drag.col):null,[game,drag?.index,drag?.row,drag?.col]);
 const linePreview=drag&&ghost&&drag.index!==-1?previewLines(game.board,ghost.shape,drag.row,drag.col):[];
 return <main className="shell"><header className="topbar"><a className="brand" href={`${process.env.NEXT_PUBLIC_BASE_PATH||''}/`} aria-label="Block Turn — главная"><span className="brand-icon"><i/><i/><i/><i/></span>block<span>turn</span><sup>↻</sup></a><span className="top-caption">МАЛЕНЬКИЙ ПОВОРОТ. НОВЫЕ ВОЗМОЖНОСТИ.</span><button className="icon-button" aria-label="Правила игры" onClick={()=>setModal('help')}><HelpCircle size={20}/></button></header>
 <section className="game-layout"><aside className="intro"><div className="eyebrow"><span/> КЛАССИКА С ПОВОРОТОМ</div><h1>Всё в твоих<br/><em>поворотах.</em></h1><p>Собирай линии. Освобождай поле.<br/>Находи место для каждой фигуры.</p><div className="tip-card"><span className="tip-icon"><RotateCw size={25}/></span><div><strong>Не помещается? Поверни.</strong><p>Нажми на фигуру внизу,<br/>чтобы повернуть её на 90°.</p></div></div><div className="mini-instruction"><span>01</span> Нажми, чтобы повернуть.<br/><span>02</span> Перетащи на поле.<br/><span>03</span> Заполни строку или столбец.</div><div className="relax"><span/> Без таймера. В своём ритме.</div></aside>
 <section className="play-area" aria-label="Игра Block Turn" onContextMenu={e=>e.preventDefault()}><div className="scorebar"><div><span className="score-label">ТВОЙ СЧЁТ</span><strong className="score">{game.score.toLocaleString('ru-RU')}</strong></div><div className="power-ups"><div className="header-bombs">{event?.bomb&&<span key={event.id} className="bomb-reward-ring" aria-hidden="true"><i/><i/><i/><b>✦</b></span>}<button className={`bomb-button ${game.bombs===1?'available':''} ${bombOnly?'last-resort':''} ${game.goldenBomb?'golden':''} ${selected===-1?'armed':''}`} disabled={!ready||game.bombs===0||!!modal} aria-label={game.bombs===1?`${game.goldenBomb?'Золотая бомба 5×5':'Бомба 3×3'} доступна. Перетащите на поле или нажмите для выбора`:'Бомбы нет. Очистите линии три хода подряд'} title={game.bombs===1?`${game.goldenBomb?'Золотая бомба 5×5':'Бомба 3×3'} — перетащи на поле`:'Бомба за три хода подряд с очисткой'} aria-pressed={selected===-1} {...dragHandlers(-1)} onClick={e=>{if(e.detail===0)setSelected(s=>s===-1?null:-1);}} onKeyDown={e=>{if(e.key==='Escape')setSelected(null);}}><Bomb size={23}/>{game.goldenBomb&&<span className="gold-star" aria-hidden="true">✦</span>}</button></div><div className="header-reroll">{event?.reroll&&<span key={event.id} className="reroll-reward" aria-hidden="true"><i/><i/></span>}<button className={`reroll-button ${game.rerolls?'available':''} ${rerollMode?'armed':''}`} disabled={!ready||!game.rerolls||!!modal||swapping!==null} aria-pressed={rerollMode} aria-label={game.rerolls?'Реролл: выбрать фигуру для замены':'Реролла нет. Очисти две линии одним ходом'} onClick={toggleReroll}><Shuffle size={22}/></button></div></div><div className="record"><Trophy size={17}/><span>РЕКОРД<strong>{best.toLocaleString('ru-RU')}</strong></span></div><button className="icon-button" onClick={toggleSound} aria-pressed={sound} aria-label={sound?'Выключить звук':'Включить звук'}>{sound?<Volume2 size={19}/>:<VolumeX size={19}/>}</button></div>
 <div className={`board-wrap ${risk?'risk-'+risk:''} ${over&&!showGameOver?'board-ending':''}`}><div ref={boardRef} className="board" role="group" aria-label="Поле 8 на 8">{game.board.flatMap((r,y)=>r.map((v,x)=>{const highlighted=drag?.index===-1?blast.includes(y*8+x):!!(drag&&ghost&&ghost.shape[y-drag.row]?.[x-drag.col]);return <button key={y*8+x} className={`cell ${v?'block color-'+v:''} ${highlighted?(valid?'preview color-'+ghost!.color:'invalid'):''} ${flash.includes(y*8+x)?'cleared':''} ${linePreview.includes(y*8+x)?'line-preview':''} ${stamped.includes(y*8+x)&&!flash.includes(y*8+x)?'stamped':''} ${flash.includes(y*8+x)&&clearRows.includes(y)&&clearCols.includes(x)?'cross-flash':''}`} style={{'--scatter-x':`${(x-3.5)*19}px`,'--scatter-y':`${(y-3.5)*16+45}px`,'--scatter-angle':`${((x*13+y*7)%45)-22}deg`,animationDelay:over&&!showGameOver?`${(x+y)*9}ms`:flash.includes(y*8+x)?`${(clearRows.length===1&&clearCols.length===1?Math.abs(x-clearCols[0])+Math.abs(y-clearRows[0]):clearRows.includes(y)?x:y)*22}ms`:stamped.includes(y*8+x)?`${stamped.indexOf(y*8+x)*18}ms`:undefined} as CSSProperties} aria-label={`Строка ${y+1}, столбец ${x+1}, ${v?'занято':'свободно'}`} onClick={()=>{if(selected!==null&&!over&&!put(selected,y,x))message('Здесь не помещается');}}/>;}))}</div>{event?.title&&<div key={event.id} className={`move-event event-${event.kind} tier-${event.tier}`} style={{'--event-duration':`${event.duration}ms`} as CSSProperties} role="status"><div className="event-shine"/>{Array.from({length:event.tier===1?5:event.tier===2?10:20},(_,i)=><i key={i} className="event-particle" style={{left:`${event.classification==='masterful'&&event.colsCleared.length?8+event.colsCleared[i%event.colsCleared.length]*11.5:5+(i*31)%90}%`,top:`${event.classification==='masterful'&&event.rowsCleared.length?8+event.rowsCleared[i%event.rowsCleared.length]*11.5:10+(i*23)%80}%`,animationDelay:`${i*.025}s`}}>✦</i>)}<div className="event-caption"><strong>{event.title}</strong><span>{event.details}</span><small className="event-score">+{event.points}</small></div></div>}<div className={`score-pop ${notice?'show':''}`} role="status">{notice}</div>{over&&showGameOver&&<div className="game-over"><Sparkles size={30}/><h2>Хорошая партия!</h2><p>Для оставшихся фигур нет места,<br/>а бомбы и реролл закончились.</p><strong>{game.score} <small>очков</small></strong><button className="primary" onClick={newGame}>Сыграть ещё <ArrowUpRight size={19}/></button></div>}</div>
 <div className="tray-heading"><span>ТВОИ ФИГУРЫ</span><span><RotateCw size={13}/> касание = поворот</span></div><div className="waiting-zone" ref={trayRef}><div className={`tray ${rerollMode?'reroll-select':''}`} key={hand}>{game.pieces.map((p,index)=><button key={index} className={`piece-slot ${selected===index?'selected':''} ${drag?.index===index?'dragging':''} ${swapping===index?'swapping':''} ${rotating===index?'rotating':''}`} style={{animationDelay:`${index*60}ms`}} disabled={!p||over||!ready||!!modal||swapping!==null} aria-label={p?`Фигура ${index+1}. ${rerollMode?'Нажмите для замены':'Нажмите для поворота или перетащите на поле'}`:'Фигура установлена'} onKeyDown={e=>{if(e.key==='Escape')setSelected(null);}} onClick={e=>{if(e.detail===0&&p)turn(index);}} {...dragHandlers(index)}>{p?<><Blocks key={rotating===index?rotationVersion:undefined} shape={p.shape} color={p.color}/><RotateCw className="rotate-hint" size={14}/></>:<span className="used" aria-hidden="true"><Check size={24}/></span>}</button>)}</div></div>
 <p className={`mobile-tip ${rerollMode?'reroll-tip':''}`}>{rerollMode?'Выбери фигуру для замены':selected===-1?'Нажми на поле, чтобы взорвать бомбу.':'Касание — поворот. Веди палец, чтобы поставить фигуру.'}</p><div className="game-footer"><span><span className="status-dot"/> {game.combo>=2?`Комбо ×${game.combo} · `:''}{game.lines} {game.lines===1?'линия':'линий'} собрано</span><button onClick={()=>setModal('restart')}><RotateCw size={15}/> Новая игра</button></div><PwaStatus/></section><div className="right-note"><span>↻</span><p>Другой угол.<br/>Новый ход.</p></div></section><footer className="page-footer"><span>BLOCK TURN</span><span>Ещё один ход — и всё сложится.</span><span>8 × 8 / БЕЗ СПЕШКИ</span></footer>
 {drag&&ghost&&<div className="floating-piece" style={{left:drag.x,top:drag.y}}>{drag.index===-1?<span className={`flying-bomb ${game.goldenBomb?'golden':''}`} style={{width:drag.size,height:drag.size}}><Bomb size={32}/></span>:<Blocks shape={ghost.shape} color={ghost.color} size={drag.size-4}/>}</div>}
 {modal&&<div className="modal-backdrop" onClick={()=>setModal(null)}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="dialog-title" onClick={e=>e.stopPropagation()} onKeyDown={e=>{if(e.key==='Escape')setModal(null);}}><button autoFocus className="icon-button close" aria-label="Закрыть" onClick={()=>setModal(null)}><X size={21}/></button><RotateCw className="modal-icon" size={32}/><h2 id="dialog-title">{modal==='help'?'Каждый поворот — возможность':'Начать заново?'}</h2>{modal==='help'?<><p>Перетаскивай фигуры на свободные клетки. Полностью заполненные строки и столбцы исчезают.</p><p><b>Нажатие на фигуру в зоне ожидания поворачивает её на 90°.</b> Вращать можно сколько угодно. На поле фигуры уже неподвижны.</p><p>После трёх установленных фигур появятся новые. Если на поле есть свободное место, хотя бы одну фигуру нового набора можно разместить с учётом поворотов. Очищай линии ход за ходом, чтобы получать бонус за комбо.</p><p><b>Очисти две линии одним ходом — получишь замену фигуры.</b> Можно хранить один реролл. Нажми Shuffle, затем выбери оставшуюся фигуру: она заменится на размещаемую. Повторное нажатие или Escape отменяет выбор. Очки и комбо не меняются.</p><p>На старте бомбы нет. Каждые три установки фигур подряд с очисткой линий дают бомбу, если её ещё нет. Можно хранить только одну. Серая кнопка означает, что бомбы нет, подсвеченная — что она готова: перетащи бомбу в любое место поля или выбери её и нажми клетку. Взрыв очищает квадрат 3×3, у края он сдвигается внутрь поля. Бомба не сбрасывает серию и не продвигает её.</p><p>Полностью очисти поле установкой фигуры, чтобы получить золотую бомбу 5×5. Очистка взрывом новую бомбу не даёт. Она заменяет обычную: хранится по-прежнему только одна. Повторный взрыв на уже пустом поле награду не даёт.</p><p>На телефоне фигура перемещается относительно движения пальца с небольшим усилением ×1,5. Заведи её на поле снизу. Чтобы отменить перенос, выведи фигуру обратно за нижний край. Бомба переносится сверху; её также можно выбрать нажатием, а затем нажать нужную клетку.</p><p className="muted">Можно играть без перетаскивания: выбери фигуру нажатием, затем нажми клетку для её верхнего левого угла. С клавиатуры — Tab и Enter.</p><button className="primary" onClick={()=>setModal(null)}>Всё понятно, играем</button></>:<><p>Текущая партия завершится. Рекорд сохранится.</p><button className="primary" onClick={newGame}>Начать новую игру</button><button className="secondary" onClick={()=>setModal(null)}>Продолжить партию</button></>}</section></div>}
 </main>;
}
